// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Ambulance Management API
 * API contract for ambulance management modules including fleet and dispatch management.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: your_email@stuba.sk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DispatchStatus } from './DispatchStatus';
import {
    DispatchStatusFromJSON,
    DispatchStatusFromJSONTyped,
    DispatchStatusToJSON,
} from './DispatchStatus';

/**
 * 
 * @export
 * @interface DispatchStatusUpdateRequest
 */
export interface DispatchStatusUpdateRequest {
    /**
     * 
     * @type {DispatchStatus}
     * @memberof DispatchStatusUpdateRequest
     */
    status: DispatchStatus;
}

/**
 * Check if a given object implements the DispatchStatusUpdateRequest interface.
 */
export function instanceOfDispatchStatusUpdateRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "status" in value;

    return isInstance;
}

export function DispatchStatusUpdateRequestFromJSON(json: any): DispatchStatusUpdateRequest {
    return DispatchStatusUpdateRequestFromJSONTyped(json, false);
}

export function DispatchStatusUpdateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DispatchStatusUpdateRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'status': DispatchStatusFromJSON(json['status']),
    };
}

export function DispatchStatusUpdateRequestToJSON(value?: DispatchStatusUpdateRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'status': DispatchStatusToJSON(value.status),
    };
}

