// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Ambulance Management API
 * API contract for ambulance management modules including fleet and dispatch management.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: your_email@stuba.sk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DispatchPriority } from './DispatchPriority';
import {
    DispatchPriorityFromJSON,
    DispatchPriorityFromJSONTyped,
    DispatchPriorityToJSON,
} from './DispatchPriority';
import type { DispatchStatus } from './DispatchStatus';
import {
    DispatchStatusFromJSON,
    DispatchStatusFromJSONTyped,
    DispatchStatusToJSON,
} from './DispatchStatus';

/**
 * 
 * @export
 * @interface DispatchCreateRequest
 */
export interface DispatchCreateRequest {
    /**
     * 
     * @type {string}
     * @memberof DispatchCreateRequest
     */
    incidentNumber: string;
    /**
     * 
     * @type {string}
     * @memberof DispatchCreateRequest
     */
    callerName: string;
    /**
     * 
     * @type {string}
     * @memberof DispatchCreateRequest
     */
    patientName: string;
    /**
     * 
     * @type {string}
     * @memberof DispatchCreateRequest
     */
    streetAddress: string;
    /**
     * 
     * @type {string}
     * @memberof DispatchCreateRequest
     */
    city: string;
    /**
     * 
     * @type {string}
     * @memberof DispatchCreateRequest
     */
    dispatchReason: string;
    /**
     * 
     * @type {DispatchPriority}
     * @memberof DispatchCreateRequest
     */
    priority: DispatchPriority;
    /**
     * 
     * @type {DispatchStatus}
     * @memberof DispatchCreateRequest
     */
    status: DispatchStatus;
    /**
     * 
     * @type {string}
     * @memberof DispatchCreateRequest
     */
    ambulanceCallSign: string;
    /**
     * 
     * @type {string}
     * @memberof DispatchCreateRequest
     */
    destinationHospital: string;
    /**
     * 
     * @type {string}
     * @memberof DispatchCreateRequest
     */
    dispatcherName: string;
    /**
     * 
     * @type {Date}
     * @memberof DispatchCreateRequest
     */
    createdAt: Date;
    /**
     * 
     * @type {string}
     * @memberof DispatchCreateRequest
     */
    notes?: string;
}

/**
 * Check if a given object implements the DispatchCreateRequest interface.
 */
export function instanceOfDispatchCreateRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "incidentNumber" in value;
    isInstance = isInstance && "callerName" in value;
    isInstance = isInstance && "patientName" in value;
    isInstance = isInstance && "streetAddress" in value;
    isInstance = isInstance && "city" in value;
    isInstance = isInstance && "dispatchReason" in value;
    isInstance = isInstance && "priority" in value;
    isInstance = isInstance && "status" in value;
    isInstance = isInstance && "ambulanceCallSign" in value;
    isInstance = isInstance && "destinationHospital" in value;
    isInstance = isInstance && "dispatcherName" in value;
    isInstance = isInstance && "createdAt" in value;

    return isInstance;
}

export function DispatchCreateRequestFromJSON(json: any): DispatchCreateRequest {
    return DispatchCreateRequestFromJSONTyped(json, false);
}

export function DispatchCreateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DispatchCreateRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'incidentNumber': json['incidentNumber'],
        'callerName': json['callerName'],
        'patientName': json['patientName'],
        'streetAddress': json['streetAddress'],
        'city': json['city'],
        'dispatchReason': json['dispatchReason'],
        'priority': DispatchPriorityFromJSON(json['priority']),
        'status': DispatchStatusFromJSON(json['status']),
        'ambulanceCallSign': json['ambulanceCallSign'],
        'destinationHospital': json['destinationHospital'],
        'dispatcherName': json['dispatcherName'],
        'createdAt': (new Date(json['createdAt'])),
        'notes': !exists(json, 'notes') ? undefined : json['notes'],
    };
}

export function DispatchCreateRequestToJSON(value?: DispatchCreateRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'incidentNumber': value.incidentNumber,
        'callerName': value.callerName,
        'patientName': value.patientName,
        'streetAddress': value.streetAddress,
        'city': value.city,
        'dispatchReason': value.dispatchReason,
        'priority': DispatchPriorityToJSON(value.priority),
        'status': DispatchStatusToJSON(value.status),
        'ambulanceCallSign': value.ambulanceCallSign,
        'destinationHospital': value.destinationHospital,
        'dispatcherName': value.dispatcherName,
        'createdAt': (value.createdAt.toISOString()),
        'notes': value.notes,
    };
}

