// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Ambulance Management API
 * API contract for ambulance management modules including fleet and dispatch management.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: your_email@stuba.sk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Supported ambulance dispatch workflow states.
 * @export
 */
export const DispatchStatus = {
    Accepted: 'ACCEPTED',
    EnRoute: 'EN_ROUTE',
    OnScene: 'ON_SCENE',
    TransportingToHospital: 'TRANSPORTING_TO_HOSPITAL',
    Completed: 'COMPLETED'
} as const;
export type DispatchStatus = typeof DispatchStatus[keyof typeof DispatchStatus];


export function DispatchStatusFromJSON(json: any): DispatchStatus {
    return DispatchStatusFromJSONTyped(json, false);
}

export function DispatchStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): DispatchStatus {
    return json as DispatchStatus;
}

export function DispatchStatusToJSON(value?: DispatchStatus | null): any {
    return value as any;
}

