// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Ambulance Management API
 * API contract for ambulance management modules including fleet and dispatch management.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: your_email@stuba.sk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { VehicleStatus } from './VehicleStatus';
import {
    VehicleStatusFromJSON,
    VehicleStatusFromJSONTyped,
    VehicleStatusToJSON,
} from './VehicleStatus';

/**
 * 
 * @export
 * @interface VehicleCreateRequest
 */
export interface VehicleCreateRequest {
    /**
     * 
     * @type {string}
     * @memberof VehicleCreateRequest
     */
    callSign: string;
    /**
     * 
     * @type {string}
     * @memberof VehicleCreateRequest
     */
    vehicleType: string;
    /**
     * 
     * @type {string}
     * @memberof VehicleCreateRequest
     */
    plateNumber: string;
    /**
     * 
     * @type {string}
     * @memberof VehicleCreateRequest
     */
    station: string;
    /**
     * 
     * @type {string}
     * @memberof VehicleCreateRequest
     */
    assignedCrew?: string;
    /**
     * 
     * @type {VehicleStatus}
     * @memberof VehicleCreateRequest
     */
    status: VehicleStatus;
    /**
     * 
     * @type {number}
     * @memberof VehicleCreateRequest
     */
    mileageKm: number;
    /**
     * 
     * @type {Date}
     * @memberof VehicleCreateRequest
     */
    lastServiceDate: Date;
    /**
     * 
     * @type {string}
     * @memberof VehicleCreateRequest
     */
    notes?: string;
}

/**
 * Check if a given object implements the VehicleCreateRequest interface.
 */
export function instanceOfVehicleCreateRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "callSign" in value;
    isInstance = isInstance && "vehicleType" in value;
    isInstance = isInstance && "plateNumber" in value;
    isInstance = isInstance && "station" in value;
    isInstance = isInstance && "status" in value;
    isInstance = isInstance && "mileageKm" in value;
    isInstance = isInstance && "lastServiceDate" in value;

    return isInstance;
}

export function VehicleCreateRequestFromJSON(json: any): VehicleCreateRequest {
    return VehicleCreateRequestFromJSONTyped(json, false);
}

export function VehicleCreateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): VehicleCreateRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'callSign': json['callSign'],
        'vehicleType': json['vehicleType'],
        'plateNumber': json['plateNumber'],
        'station': json['station'],
        'assignedCrew': !exists(json, 'assignedCrew') ? undefined : json['assignedCrew'],
        'status': VehicleStatusFromJSON(json['status']),
        'mileageKm': json['mileageKm'],
        'lastServiceDate': (new Date(json['lastServiceDate'])),
        'notes': !exists(json, 'notes') ? undefined : json['notes'],
    };
}

export function VehicleCreateRequestToJSON(value?: VehicleCreateRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'callSign': value.callSign,
        'vehicleType': value.vehicleType,
        'plateNumber': value.plateNumber,
        'station': value.station,
        'assignedCrew': value.assignedCrew,
        'status': VehicleStatusToJSON(value.status),
        'mileageKm': value.mileageKm,
        'lastServiceDate': (value.lastServiceDate.toISOString().substr(0,10)),
        'notes': value.notes,
    };
}
