// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Ambulance Management API
 * API contract for ambulance management modules including fleet and dispatch management.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: your_email@stuba.sk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Supported vehicle lifecycle and availability states.
 * @export
 */
export const VehicleStatus = {
    Available: 'AVAILABLE',
    OnMission: 'ON_MISSION',
    OutOfService: 'OUT_OF_SERVICE',
    InService: 'IN_SERVICE'
} as const;
export type VehicleStatus = typeof VehicleStatus[keyof typeof VehicleStatus];


export function VehicleStatusFromJSON(json: any): VehicleStatus {
    return VehicleStatusFromJSONTyped(json, false);
}

export function VehicleStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): VehicleStatus {
    return json as VehicleStatus;
}

export function VehicleStatusToJSON(value?: VehicleStatus | null): any {
    return value as any;
}
