// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Ambulance Management API
 * API contract for ambulance management modules including fleet and dispatch management.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: your_email@stuba.sk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { VehicleStatus } from './VehicleStatus';
import {
    VehicleStatusFromJSON,
    VehicleStatusFromJSONTyped,
    VehicleStatusToJSON,
} from './VehicleStatus';

/**
 * 
 * @export
 * @interface VehicleStatusUpdateRequest
 */
export interface VehicleStatusUpdateRequest {
    /**
     * 
     * @type {VehicleStatus}
     * @memberof VehicleStatusUpdateRequest
     */
    status: VehicleStatus;
}

/**
 * Check if a given object implements the VehicleStatusUpdateRequest interface.
 */
export function instanceOfVehicleStatusUpdateRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "status" in value;

    return isInstance;
}

export function VehicleStatusUpdateRequestFromJSON(json: any): VehicleStatusUpdateRequest {
    return VehicleStatusUpdateRequestFromJSONTyped(json, false);
}

export function VehicleStatusUpdateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): VehicleStatusUpdateRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'status': VehicleStatusFromJSON(json['status']),
    };
}

export function VehicleStatusUpdateRequestToJSON(value?: VehicleStatusUpdateRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'status': VehicleStatusToJSON(value.status),
    };
}

