// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Ambulance Management API
 * API contract for ambulance management modules including fleet and dispatch management.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: your_email@stuba.sk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Vehicle,
  VehicleCreateRequest,
  VehicleStatus,
  VehicleStatusUpdateRequest,
  VehicleUpdateRequest,
} from '../models';
import {
    VehicleFromJSON,
    VehicleToJSON,
    VehicleCreateRequestFromJSON,
    VehicleCreateRequestToJSON,
    VehicleStatusFromJSON,
    VehicleStatusToJSON,
    VehicleStatusUpdateRequestFromJSON,
    VehicleStatusUpdateRequestToJSON,
    VehicleUpdateRequestFromJSON,
    VehicleUpdateRequestToJSON,
} from '../models';

export interface VehiclesGetRequest {
    status?: VehicleStatus;
    station?: string;
}

export interface VehiclesPostRequest {
    vehicleCreateRequest: VehicleCreateRequest;
}

export interface VehiclesVehicleIdDeleteRequest {
    vehicleId: number;
}

export interface VehiclesVehicleIdGetRequest {
    vehicleId: number;
}

export interface VehiclesVehicleIdPutRequest {
    vehicleId: number;
    vehicleUpdateRequest: VehicleUpdateRequest;
}

export interface VehiclesVehicleIdStatusPatchRequest {
    vehicleId: number;
    vehicleStatusUpdateRequest: VehicleStatusUpdateRequest;
}

/**
 * AmbulanceManagementApi - interface
 * 
 * @export
 * @interface AmbulanceManagementApiInterface
 */
export interface AmbulanceManagementApiInterface {
    /**
     * Returns the registered ambulance vehicles with optional filtering by operational status and station.
     * @summary List ambulance vehicles
     * @param {VehicleStatus} [status] Filter vehicles by current operational status.
     * @param {string} [station] Filter vehicles by assigned station.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AmbulanceManagementApiInterface
     */
    vehiclesGetRaw(requestParameters: VehiclesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Vehicle>>>;

    /**
     * Returns the registered ambulance vehicles with optional filtering by operational status and station.
     * List ambulance vehicles
     */
    vehiclesGet(requestParameters: VehiclesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Vehicle>>;

    /**
     * Adds a new ambulance vehicle to the fleet registry.
     * @summary Register a new ambulance vehicle
     * @param {VehicleCreateRequest} vehicleCreateRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AmbulanceManagementApiInterface
     */
    vehiclesPostRaw(requestParameters: VehiclesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Vehicle>>;

    /**
     * Adds a new ambulance vehicle to the fleet registry.
     * Register a new ambulance vehicle
     */
    vehiclesPost(requestParameters: VehiclesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Vehicle>;

    /**
     * Retires an ambulance vehicle that is no longer in service.
     * @summary Remove ambulance vehicle from registry
     * @param {number} vehicleId Internal vehicle identifier.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AmbulanceManagementApiInterface
     */
    vehiclesVehicleIdDeleteRaw(requestParameters: VehiclesVehicleIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Retires an ambulance vehicle that is no longer in service.
     * Remove ambulance vehicle from registry
     */
    vehiclesVehicleIdDelete(requestParameters: VehiclesVehicleIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Returns technical and operational detail of a specific ambulance vehicle.
     * @summary Get ambulance vehicle detail
     * @param {number} vehicleId Internal vehicle identifier.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AmbulanceManagementApiInterface
     */
    vehiclesVehicleIdGetRaw(requestParameters: VehiclesVehicleIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Vehicle>>;

    /**
     * Returns technical and operational detail of a specific ambulance vehicle.
     * Get ambulance vehicle detail
     */
    vehiclesVehicleIdGet(requestParameters: VehiclesVehicleIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Vehicle>;

    /**
     * Updates editable ambulance vehicle data including technical information and current status.
     * @summary Update ambulance vehicle
     * @param {number} vehicleId Internal vehicle identifier.
     * @param {VehicleUpdateRequest} vehicleUpdateRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AmbulanceManagementApiInterface
     */
    vehiclesVehicleIdPutRaw(requestParameters: VehiclesVehicleIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Vehicle>>;

    /**
     * Updates editable ambulance vehicle data including technical information and current status.
     * Update ambulance vehicle
     */
    vehiclesVehicleIdPut(requestParameters: VehiclesVehicleIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Vehicle>;

    /**
     * Changes only the operational status of the ambulance vehicle.
     * @summary Update ambulance vehicle status
     * @param {number} vehicleId Internal vehicle identifier.
     * @param {VehicleStatusUpdateRequest} vehicleStatusUpdateRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AmbulanceManagementApiInterface
     */
    vehiclesVehicleIdStatusPatchRaw(requestParameters: VehiclesVehicleIdStatusPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Vehicle>>;

    /**
     * Changes only the operational status of the ambulance vehicle.
     * Update ambulance vehicle status
     */
    vehiclesVehicleIdStatusPatch(requestParameters: VehiclesVehicleIdStatusPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Vehicle>;

}

/**
 * 
 */
export class AmbulanceManagementApi extends runtime.BaseAPI implements AmbulanceManagementApiInterface {

    /**
     * Returns the registered ambulance vehicles with optional filtering by operational status and station.
     * List ambulance vehicles
     */
    async vehiclesGetRaw(requestParameters: VehiclesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Vehicle>>> {
        const queryParameters: any = {};

        if (requestParameters.status !== undefined) {
            queryParameters['status'] = requestParameters.status;
        }

        if (requestParameters.station !== undefined) {
            queryParameters['station'] = requestParameters.station;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/vehicles`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(VehicleFromJSON));
    }

    /**
     * Returns the registered ambulance vehicles with optional filtering by operational status and station.
     * List ambulance vehicles
     */
    async vehiclesGet(requestParameters: VehiclesGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Vehicle>> {
        const response = await this.vehiclesGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Adds a new ambulance vehicle to the fleet registry.
     * Register a new ambulance vehicle
     */
    async vehiclesPostRaw(requestParameters: VehiclesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Vehicle>> {
        if (requestParameters.vehicleCreateRequest === null || requestParameters.vehicleCreateRequest === undefined) {
            throw new runtime.RequiredError('vehicleCreateRequest','Required parameter requestParameters.vehicleCreateRequest was null or undefined when calling vehiclesPost.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/vehicles`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: VehicleCreateRequestToJSON(requestParameters.vehicleCreateRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => VehicleFromJSON(jsonValue));
    }

    /**
     * Adds a new ambulance vehicle to the fleet registry.
     * Register a new ambulance vehicle
     */
    async vehiclesPost(requestParameters: VehiclesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Vehicle> {
        const response = await this.vehiclesPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retires an ambulance vehicle that is no longer in service.
     * Remove ambulance vehicle from registry
     */
    async vehiclesVehicleIdDeleteRaw(requestParameters: VehiclesVehicleIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.vehicleId === null || requestParameters.vehicleId === undefined) {
            throw new runtime.RequiredError('vehicleId','Required parameter requestParameters.vehicleId was null or undefined when calling vehiclesVehicleIdDelete.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/vehicles/{vehicleId}`.replace(`{${"vehicleId"}}`, encodeURIComponent(String(requestParameters.vehicleId))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Retires an ambulance vehicle that is no longer in service.
     * Remove ambulance vehicle from registry
     */
    async vehiclesVehicleIdDelete(requestParameters: VehiclesVehicleIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.vehiclesVehicleIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Returns technical and operational detail of a specific ambulance vehicle.
     * Get ambulance vehicle detail
     */
    async vehiclesVehicleIdGetRaw(requestParameters: VehiclesVehicleIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Vehicle>> {
        if (requestParameters.vehicleId === null || requestParameters.vehicleId === undefined) {
            throw new runtime.RequiredError('vehicleId','Required parameter requestParameters.vehicleId was null or undefined when calling vehiclesVehicleIdGet.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/vehicles/{vehicleId}`.replace(`{${"vehicleId"}}`, encodeURIComponent(String(requestParameters.vehicleId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => VehicleFromJSON(jsonValue));
    }

    /**
     * Returns technical and operational detail of a specific ambulance vehicle.
     * Get ambulance vehicle detail
     */
    async vehiclesVehicleIdGet(requestParameters: VehiclesVehicleIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Vehicle> {
        const response = await this.vehiclesVehicleIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Updates editable ambulance vehicle data including technical information and current status.
     * Update ambulance vehicle
     */
    async vehiclesVehicleIdPutRaw(requestParameters: VehiclesVehicleIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Vehicle>> {
        if (requestParameters.vehicleId === null || requestParameters.vehicleId === undefined) {
            throw new runtime.RequiredError('vehicleId','Required parameter requestParameters.vehicleId was null or undefined when calling vehiclesVehicleIdPut.');
        }

        if (requestParameters.vehicleUpdateRequest === null || requestParameters.vehicleUpdateRequest === undefined) {
            throw new runtime.RequiredError('vehicleUpdateRequest','Required parameter requestParameters.vehicleUpdateRequest was null or undefined when calling vehiclesVehicleIdPut.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/vehicles/{vehicleId}`.replace(`{${"vehicleId"}}`, encodeURIComponent(String(requestParameters.vehicleId))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: VehicleUpdateRequestToJSON(requestParameters.vehicleUpdateRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => VehicleFromJSON(jsonValue));
    }

    /**
     * Updates editable ambulance vehicle data including technical information and current status.
     * Update ambulance vehicle
     */
    async vehiclesVehicleIdPut(requestParameters: VehiclesVehicleIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Vehicle> {
        const response = await this.vehiclesVehicleIdPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Changes only the operational status of the ambulance vehicle.
     * Update ambulance vehicle status
     */
    async vehiclesVehicleIdStatusPatchRaw(requestParameters: VehiclesVehicleIdStatusPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Vehicle>> {
        if (requestParameters.vehicleId === null || requestParameters.vehicleId === undefined) {
            throw new runtime.RequiredError('vehicleId','Required parameter requestParameters.vehicleId was null or undefined when calling vehiclesVehicleIdStatusPatch.');
        }

        if (requestParameters.vehicleStatusUpdateRequest === null || requestParameters.vehicleStatusUpdateRequest === undefined) {
            throw new runtime.RequiredError('vehicleStatusUpdateRequest','Required parameter requestParameters.vehicleStatusUpdateRequest was null or undefined when calling vehiclesVehicleIdStatusPatch.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/vehicles/{vehicleId}/status`.replace(`{${"vehicleId"}}`, encodeURIComponent(String(requestParameters.vehicleId))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: VehicleStatusUpdateRequestToJSON(requestParameters.vehicleStatusUpdateRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => VehicleFromJSON(jsonValue));
    }

    /**
     * Changes only the operational status of the ambulance vehicle.
     * Update ambulance vehicle status
     */
    async vehiclesVehicleIdStatusPatch(requestParameters: VehiclesVehicleIdStatusPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Vehicle> {
        const response = await this.vehiclesVehicleIdStatusPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
