// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Ambulance Management API
 * API contract for ambulance management modules including fleet and dispatch management.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: your_email@stuba.sk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Dispatch,
  DispatchCreateRequest,
  DispatchStatus,
  DispatchStatusUpdateRequest,
  DispatchUpdateRequest,
} from '../models';
import {
    DispatchFromJSON,
    DispatchToJSON,
    DispatchCreateRequestFromJSON,
    DispatchCreateRequestToJSON,
    DispatchStatusFromJSON,
    DispatchStatusToJSON,
    DispatchStatusUpdateRequestFromJSON,
    DispatchStatusUpdateRequestToJSON,
    DispatchUpdateRequestFromJSON,
    DispatchUpdateRequestToJSON,
} from '../models';

export interface DispatchesDispatchIdDeleteRequest {
    dispatchId: number;
}

export interface DispatchesDispatchIdGetRequest {
    dispatchId: number;
}

export interface DispatchesDispatchIdPutRequest {
    dispatchId: number;
    dispatchUpdateRequest: DispatchUpdateRequest;
}

export interface DispatchesDispatchIdStatusPatchRequest {
    dispatchId: number;
    dispatchStatusUpdateRequest: DispatchStatusUpdateRequest;
}

export interface DispatchesGetRequest {
    status?: DispatchStatus;
    city?: string;
}

export interface DispatchesPostRequest {
    dispatchCreateRequest: DispatchCreateRequest;
}

/**
 * DispatchManagementApi - interface
 * 
 * @export
 * @interface DispatchManagementApiInterface
 */
export interface DispatchManagementApiInterface {
    /**
     * Cancels a dispatch that was created by mistake or is no longer needed.
     * @summary Cancel ambulance dispatch
     * @param {number} dispatchId Internal dispatch identifier.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DispatchManagementApiInterface
     */
    dispatchesDispatchIdDeleteRaw(requestParameters: DispatchesDispatchIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Cancels a dispatch that was created by mistake or is no longer needed.
     * Cancel ambulance dispatch
     */
    dispatchesDispatchIdDelete(requestParameters: DispatchesDispatchIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Returns detail of a specific ambulance dispatch.
     * @summary Get ambulance dispatch detail
     * @param {number} dispatchId Internal dispatch identifier.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DispatchManagementApiInterface
     */
    dispatchesDispatchIdGetRaw(requestParameters: DispatchesDispatchIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Dispatch>>;

    /**
     * Returns detail of a specific ambulance dispatch.
     * Get ambulance dispatch detail
     */
    dispatchesDispatchIdGet(requestParameters: DispatchesDispatchIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Dispatch>;

    /**
     * Updates the editable dispatch data for an existing ambulance mission.
     * @summary Update ambulance dispatch
     * @param {number} dispatchId Internal dispatch identifier.
     * @param {DispatchUpdateRequest} dispatchUpdateRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DispatchManagementApiInterface
     */
    dispatchesDispatchIdPutRaw(requestParameters: DispatchesDispatchIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Dispatch>>;

    /**
     * Updates the editable dispatch data for an existing ambulance mission.
     * Update ambulance dispatch
     */
    dispatchesDispatchIdPut(requestParameters: DispatchesDispatchIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Dispatch>;

    /**
     * Updates only the operational status of a dispatch.
     * @summary Update ambulance dispatch status
     * @param {number} dispatchId Internal dispatch identifier.
     * @param {DispatchStatusUpdateRequest} dispatchStatusUpdateRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DispatchManagementApiInterface
     */
    dispatchesDispatchIdStatusPatchRaw(requestParameters: DispatchesDispatchIdStatusPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Dispatch>>;

    /**
     * Updates only the operational status of a dispatch.
     * Update ambulance dispatch status
     */
    dispatchesDispatchIdStatusPatch(requestParameters: DispatchesDispatchIdStatusPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Dispatch>;

    /**
     * Returns current and historical ambulance dispatches with optional filtering by status and city.
     * @summary List ambulance dispatches
     * @param {DispatchStatus} [status] Filter dispatches by current workflow status.
     * @param {string} [city] Filter dispatches by city of the incident.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DispatchManagementApiInterface
     */
    dispatchesGetRaw(requestParameters: DispatchesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Dispatch>>>;

    /**
     * Returns current and historical ambulance dispatches with optional filtering by status and city.
     * List ambulance dispatches
     */
    dispatchesGet(requestParameters: DispatchesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Dispatch>>;

    /**
     * Creates a new ambulance dispatch request for a patient incident.
     * @summary Create ambulance dispatch
     * @param {DispatchCreateRequest} dispatchCreateRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DispatchManagementApiInterface
     */
    dispatchesPostRaw(requestParameters: DispatchesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Dispatch>>;

    /**
     * Creates a new ambulance dispatch request for a patient incident.
     * Create ambulance dispatch
     */
    dispatchesPost(requestParameters: DispatchesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Dispatch>;

}

/**
 * 
 */
export class DispatchManagementApi extends runtime.BaseAPI implements DispatchManagementApiInterface {

    /**
     * Cancels a dispatch that was created by mistake or is no longer needed.
     * Cancel ambulance dispatch
     */
    async dispatchesDispatchIdDeleteRaw(requestParameters: DispatchesDispatchIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.dispatchId === null || requestParameters.dispatchId === undefined) {
            throw new runtime.RequiredError('dispatchId','Required parameter requestParameters.dispatchId was null or undefined when calling dispatchesDispatchIdDelete.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/dispatches/{dispatchId}`.replace(`{${"dispatchId"}}`, encodeURIComponent(String(requestParameters.dispatchId))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Cancels a dispatch that was created by mistake or is no longer needed.
     * Cancel ambulance dispatch
     */
    async dispatchesDispatchIdDelete(requestParameters: DispatchesDispatchIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.dispatchesDispatchIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Returns detail of a specific ambulance dispatch.
     * Get ambulance dispatch detail
     */
    async dispatchesDispatchIdGetRaw(requestParameters: DispatchesDispatchIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Dispatch>> {
        if (requestParameters.dispatchId === null || requestParameters.dispatchId === undefined) {
            throw new runtime.RequiredError('dispatchId','Required parameter requestParameters.dispatchId was null or undefined when calling dispatchesDispatchIdGet.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/dispatches/{dispatchId}`.replace(`{${"dispatchId"}}`, encodeURIComponent(String(requestParameters.dispatchId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DispatchFromJSON(jsonValue));
    }

    /**
     * Returns detail of a specific ambulance dispatch.
     * Get ambulance dispatch detail
     */
    async dispatchesDispatchIdGet(requestParameters: DispatchesDispatchIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Dispatch> {
        const response = await this.dispatchesDispatchIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Updates the editable dispatch data for an existing ambulance mission.
     * Update ambulance dispatch
     */
    async dispatchesDispatchIdPutRaw(requestParameters: DispatchesDispatchIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Dispatch>> {
        if (requestParameters.dispatchId === null || requestParameters.dispatchId === undefined) {
            throw new runtime.RequiredError('dispatchId','Required parameter requestParameters.dispatchId was null or undefined when calling dispatchesDispatchIdPut.');
        }

        if (requestParameters.dispatchUpdateRequest === null || requestParameters.dispatchUpdateRequest === undefined) {
            throw new runtime.RequiredError('dispatchUpdateRequest','Required parameter requestParameters.dispatchUpdateRequest was null or undefined when calling dispatchesDispatchIdPut.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/dispatches/{dispatchId}`.replace(`{${"dispatchId"}}`, encodeURIComponent(String(requestParameters.dispatchId))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: DispatchUpdateRequestToJSON(requestParameters.dispatchUpdateRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DispatchFromJSON(jsonValue));
    }

    /**
     * Updates the editable dispatch data for an existing ambulance mission.
     * Update ambulance dispatch
     */
    async dispatchesDispatchIdPut(requestParameters: DispatchesDispatchIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Dispatch> {
        const response = await this.dispatchesDispatchIdPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Updates only the operational status of a dispatch.
     * Update ambulance dispatch status
     */
    async dispatchesDispatchIdStatusPatchRaw(requestParameters: DispatchesDispatchIdStatusPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Dispatch>> {
        if (requestParameters.dispatchId === null || requestParameters.dispatchId === undefined) {
            throw new runtime.RequiredError('dispatchId','Required parameter requestParameters.dispatchId was null or undefined when calling dispatchesDispatchIdStatusPatch.');
        }

        if (requestParameters.dispatchStatusUpdateRequest === null || requestParameters.dispatchStatusUpdateRequest === undefined) {
            throw new runtime.RequiredError('dispatchStatusUpdateRequest','Required parameter requestParameters.dispatchStatusUpdateRequest was null or undefined when calling dispatchesDispatchIdStatusPatch.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/dispatches/{dispatchId}/status`.replace(`{${"dispatchId"}}`, encodeURIComponent(String(requestParameters.dispatchId))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: DispatchStatusUpdateRequestToJSON(requestParameters.dispatchStatusUpdateRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DispatchFromJSON(jsonValue));
    }

    /**
     * Updates only the operational status of a dispatch.
     * Update ambulance dispatch status
     */
    async dispatchesDispatchIdStatusPatch(requestParameters: DispatchesDispatchIdStatusPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Dispatch> {
        const response = await this.dispatchesDispatchIdStatusPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns current and historical ambulance dispatches with optional filtering by status and city.
     * List ambulance dispatches
     */
    async dispatchesGetRaw(requestParameters: DispatchesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Dispatch>>> {
        const queryParameters: any = {};

        if (requestParameters.status !== undefined) {
            queryParameters['status'] = requestParameters.status;
        }

        if (requestParameters.city !== undefined) {
            queryParameters['city'] = requestParameters.city;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/dispatches`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(DispatchFromJSON));
    }

    /**
     * Returns current and historical ambulance dispatches with optional filtering by status and city.
     * List ambulance dispatches
     */
    async dispatchesGet(requestParameters: DispatchesGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Dispatch>> {
        const response = await this.dispatchesGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates a new ambulance dispatch request for a patient incident.
     * Create ambulance dispatch
     */
    async dispatchesPostRaw(requestParameters: DispatchesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Dispatch>> {
        if (requestParameters.dispatchCreateRequest === null || requestParameters.dispatchCreateRequest === undefined) {
            throw new runtime.RequiredError('dispatchCreateRequest','Required parameter requestParameters.dispatchCreateRequest was null or undefined when calling dispatchesPost.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/dispatches`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DispatchCreateRequestToJSON(requestParameters.dispatchCreateRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DispatchFromJSON(jsonValue));
    }

    /**
     * Creates a new ambulance dispatch request for a patient incident.
     * Create ambulance dispatch
     */
    async dispatchesPost(requestParameters: DispatchesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Dispatch> {
        const response = await this.dispatchesPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
