/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AmbulanceManagementAmbulanceDispatchManagement {
    }
    interface AmbulanceManagementMainContainer {
        /**
          * @default ''
         */
        "basePath": string;
    }
    interface AmbulanceManagementParamedicVehicleManagement {
    }
}
declare global {
    interface HTMLAmbulanceManagementAmbulanceDispatchManagementElement extends Components.AmbulanceManagementAmbulanceDispatchManagement, HTMLStencilElement {
    }
    var HTMLAmbulanceManagementAmbulanceDispatchManagementElement: {
        prototype: HTMLAmbulanceManagementAmbulanceDispatchManagementElement;
        new (): HTMLAmbulanceManagementAmbulanceDispatchManagementElement;
    };
    interface HTMLAmbulanceManagementMainContainerElement extends Components.AmbulanceManagementMainContainer, HTMLStencilElement {
    }
    var HTMLAmbulanceManagementMainContainerElement: {
        prototype: HTMLAmbulanceManagementMainContainerElement;
        new (): HTMLAmbulanceManagementMainContainerElement;
    };
    interface HTMLAmbulanceManagementParamedicVehicleManagementElement extends Components.AmbulanceManagementParamedicVehicleManagement, HTMLStencilElement {
    }
    var HTMLAmbulanceManagementParamedicVehicleManagementElement: {
        prototype: HTMLAmbulanceManagementParamedicVehicleManagementElement;
        new (): HTMLAmbulanceManagementParamedicVehicleManagementElement;
    };
    interface HTMLElementTagNameMap {
        "ambulance-management-ambulance-dispatch-management": HTMLAmbulanceManagementAmbulanceDispatchManagementElement;
        "ambulance-management-main-container": HTMLAmbulanceManagementMainContainerElement;
        "ambulance-management-paramedic-vehicle-management": HTMLAmbulanceManagementParamedicVehicleManagementElement;
    }
}
declare namespace LocalJSX {
    interface AmbulanceManagementAmbulanceDispatchManagement {
    }
    interface AmbulanceManagementMainContainer {
        /**
          * @default ''
         */
        "basePath"?: string;
    }
    interface AmbulanceManagementParamedicVehicleManagement {
    }

    interface AmbulanceManagementMainContainerAttributes {
        "basePath": string;
    }

    interface IntrinsicElements {
        "ambulance-management-ambulance-dispatch-management": AmbulanceManagementAmbulanceDispatchManagement;
        "ambulance-management-main-container": Omit<AmbulanceManagementMainContainer, keyof AmbulanceManagementMainContainerAttributes> & { [K in keyof AmbulanceManagementMainContainer & keyof AmbulanceManagementMainContainerAttributes]?: AmbulanceManagementMainContainer[K] } & { [K in keyof AmbulanceManagementMainContainer & keyof AmbulanceManagementMainContainerAttributes as `attr:${K}`]?: AmbulanceManagementMainContainerAttributes[K] } & { [K in keyof AmbulanceManagementMainContainer & keyof AmbulanceManagementMainContainerAttributes as `prop:${K}`]?: AmbulanceManagementMainContainer[K] };
        "ambulance-management-paramedic-vehicle-management": AmbulanceManagementParamedicVehicleManagement;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ambulance-management-ambulance-dispatch-management": LocalJSX.IntrinsicElements["ambulance-management-ambulance-dispatch-management"] & JSXBase.HTMLAttributes<HTMLAmbulanceManagementAmbulanceDispatchManagementElement>;
            "ambulance-management-main-container": LocalJSX.IntrinsicElements["ambulance-management-main-container"] & JSXBase.HTMLAttributes<HTMLAmbulanceManagementMainContainerElement>;
            "ambulance-management-paramedic-vehicle-management": LocalJSX.IntrinsicElements["ambulance-management-paramedic-vehicle-management"] & JSXBase.HTMLAttributes<HTMLAmbulanceManagementParamedicVehicleManagementElement>;
        }
    }
}
