/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AmbulanceManagementMainContainer {
    }
}
declare global {
    interface HTMLAmbulanceManagementMainContainerElement extends Components.AmbulanceManagementMainContainer, HTMLStencilElement {
    }
    var HTMLAmbulanceManagementMainContainerElement: {
        prototype: HTMLAmbulanceManagementMainContainerElement;
        new (): HTMLAmbulanceManagementMainContainerElement;
    };
    interface HTMLElementTagNameMap {
        "ambulance-management-main-container": HTMLAmbulanceManagementMainContainerElement;
    }
}
declare namespace LocalJSX {
    interface AmbulanceManagementMainContainer {
    }
    interface IntrinsicElements {
        "ambulance-management-main-container": AmbulanceManagementMainContainer;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ambulance-management-main-container": LocalJSX.IntrinsicElements["ambulance-management-main-container"] & JSXBase.HTMLAttributes<HTMLAmbulanceManagementMainContainerElement>;
        }
    }
}
